// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class QaAutoTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void qaAuto() {
    driver.Navigate().GoToUrl("https://qauto.forstudy.space/");
    driver.Manage().Window.Size = new System.Drawing.Size(1280, 800);
    driver.FindElement(By.CssSelector(".hero-descriptor_btn")).Click();
    driver.FindElement(By.Id("signupName")).Click();
    driver.FindElement(By.Id("signupName")).SendKeys("Oleg");
    driver.FindElement(By.Id("signupLastName")).SendKeys("SHK");
    vars["email"] = js.ExecuteScript("return \"jiyewy67158314\" + Math.floor(Math.random() * 1000) + \"@lukaat.com\"");
    driver.FindElement(By.Id("signupEmail")).SendKeys(vars["email"].ToString());
    driver.FindElement(By.Id("signupPassword")).SendKeys("A123456789z");
    driver.FindElement(By.Id("signupRepeatPassword")).SendKeys("A123456789z");
    driver.FindElement(By.CssSelector(".btn-primary:nth-child(1)")).Click();
    driver.FindElement(By.LinkText("Profile")).Click();
    Assert.That(driver.FindElement(By.CssSelector("p.profile_name.display-4")).Text, Is.EqualTo("Oleg SHK"));
    driver.FindElement(By.CssSelector(".sidebar > .btn:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.Id("addCarBrand")).Click();
    {
      var dropdown = driver.FindElement(By.Id("addCarBrand"));
      dropdown.FindElement(By.XPath("//option[. = 'BMW']")).Click();
    }
    driver.FindElement(By.Id("addCarModel")).Click();
    {
      var dropdown = driver.FindElement(By.Id("addCarModel"));
      dropdown.FindElement(By.XPath("//option[. = 'X5']")).Click();
    }
    driver.FindElement(By.Id("addCarMileage")).Click();
    driver.FindElement(By.Id("addCarMileage")).SendKeys("1");
    driver.FindElement(By.Id("addCarMileage")).Click();
    driver.FindElement(By.Id("addCarMileage")).SendKeys("2");
    driver.FindElement(By.Id("addCarMileage")).Click();
    {
      var element = driver.FindElement(By.Id("addCarMileage"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.Id("addCarMileage")).SendKeys("3");
    driver.FindElement(By.Id("addCarMileage")).Click();
    driver.FindElement(By.CssSelector(".modal-footer > .btn-primary")).Click();
    driver.FindElement(By.CssSelector(".car_add-expense")).Click();
    driver.FindElement(By.Id("addExpenseMileage")).SendKeys("4");
    driver.FindElement(By.Id("addExpenseMileage")).Click();
    driver.FindElement(By.Id("addExpenseMileage")).SendKeys("5");
    driver.FindElement(By.Id("addExpenseMileage")).Click();
    {
      var element = driver.FindElement(By.Id("addExpenseMileage"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.Id("addExpenseLiters")).Click();
    driver.FindElement(By.Id("addExpenseLiters")).SendKeys("1");
    driver.FindElement(By.Id("addExpenseLiters")).Click();
    driver.FindElement(By.Id("addExpenseLiters")).SendKeys("2");
    driver.FindElement(By.Id("addExpenseLiters")).Click();
    {
      var element = driver.FindElement(By.Id("addExpenseLiters"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.Id("addExpenseLiters")).SendKeys("3");
    driver.FindElement(By.Id("addExpenseLiters")).Click();
    driver.FindElement(By.Id("addExpenseTotalCost")).Click();
    driver.FindElement(By.Id("addExpenseTotalCost")).SendKeys("1");
    driver.FindElement(By.Id("addExpenseTotalCost")).Click();
    driver.FindElement(By.Id("addExpenseTotalCost")).SendKeys("150");
    driver.FindElement(By.CssSelector(".modal-footer > .btn-primary")).Click();
    driver.FindElement(By.LinkText("Settings")).Click();
    driver.FindElement(By.CssSelector(".btn-danger-bg")).Click();
    driver.FindElement(By.CssSelector(".btn-danger")).Click();
    var elements = driver.FindElements(By.XPath("//button [@class=\"btn header-link\"]"));
    Assert.True(elements.Count > 0);
  }
}
